version: "3.9"

services:
  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "2022:5432"
  web:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    command: ["rails", "s", "-b", "0.0.0.0"]
volumes:
  dbdata:
